"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum

class AuditLogActorType(str, Enum):
    r"""Filter to events with an actor of this type.
    This only needs to be included if querying for actor types without an ID. If `actor_gid` is included, this should be excluded.
    """
    USER = 'user'
    ASANA = 'asana'
    ASANA_SUPPORT = 'asana_support'
    ANONYMOUS = 'anonymous'
    EXTERNAL_ADMINISTRATOR = 'external_administrator'
