"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses



@dataclasses.dataclass
class AuditLogEventDetails:
    r"""Event specific details. The schema will vary depending on the `event_type`."""
    

