"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ..shared import enumoption as shared_enumoption
from ..shared import usercompact as shared_usercompact
from dataclasses_json import Undefined, dataclass_json
from enum import Enum
from testing_2 import utils
from typing import Optional

class CustomFieldSettingResponseCustomFieldAsanaCreatedField(str, Enum):
    r"""*Conditional*. A unique identifier to associate this field with the template source of truth."""
    A_V_REQUIREMENTS = 'a_v_requirements'
    ACCOUNT_NAME = 'account_name'
    ACTIONABLE = 'actionable'
    ALIGN_SHIPPING_LINK = 'align_shipping_link'
    ALIGN_STATUS = 'align_status'
    ALLOTTED_TIME = 'allotted_time'
    APPOINTMENT = 'appointment'
    APPROVAL_STAGE = 'approval_stage'
    APPROVED = 'approved'
    ARTICLE_SERIES = 'article_series'
    BOARD_COMMITTEE = 'board_committee'
    BROWSER = 'browser'
    CAMPAIGN_AUDIENCE = 'campaign_audience'
    CAMPAIGN_PROJECT_STATUS = 'campaign_project_status'
    CAMPAIGN_REGIONS = 'campaign_regions'
    CHANNEL_PRIMARY = 'channel_primary'
    CLIENT_TOPIC_TYPE = 'client_topic_type'
    COMPLETE_BY = 'complete_by'
    CONTACT = 'contact'
    CONTACT_EMAIL_ADDRESS = 'contact_email_address'
    CONTENT_CHANNELS = 'content_channels'
    CONTENT_CHANNELS_NEEDED = 'content_channels_needed'
    CONTENT_STAGE = 'content_stage'
    CONTENT_TYPE = 'content_type'
    CONTRACT = 'contract'
    CONTRACT_STATUS = 'contract_status'
    COST = 'cost'
    CREATION_STAGE = 'creation_stage'
    CREATIVE_CHANNEL = 'creative_channel'
    CREATIVE_NEEDED = 'creative_needed'
    CREATIVE_NEEDS = 'creative_needs'
    DATA_SENSITIVITY = 'data_sensitivity'
    DEAL_SIZE = 'deal_size'
    DELIVERY_APPT = 'delivery_appt'
    DELIVERY_APPT_DATE = 'delivery_appt_date'
    DEPARTMENT = 'department'
    DEPARTMENT_RESPONSIBLE = 'department_responsible'
    DESIGN_REQUEST_NEEDED = 'design_request_needed'
    DESIGN_REQUEST_TYPE = 'design_request_type'
    DISCUSSION_CATEGORY = 'discussion_category'
    DO_THIS_TASK = 'do_this_task'
    EDITORIAL_CONTENT_STATUS = 'editorial_content_status'
    EDITORIAL_CONTENT_TAG = 'editorial_content_tag'
    EDITORIAL_CONTENT_TYPE = 'editorial_content_type'
    EFFORT = 'effort'
    EFFORT_LEVEL = 'effort_level'
    EST_COMPLETION_DATE = 'est_completion_date'
    ESTIMATED_TIME = 'estimated_time'
    ESTIMATED_VALUE = 'estimated_value'
    EXPECTED_COST = 'expected_cost'
    EXTERNAL_STEPS_NEEDED = 'external_steps_needed'
    FAVORITE_IDEA = 'favorite_idea'
    FEEDBACK_TYPE = 'feedback_type'
    FINANCIAL = 'financial'
    FUNDING_AMOUNT = 'funding_amount'
    GRANT_APPLICATION_PROCESS = 'grant_application_process'
    HIRING_CANDIDATE_STATUS = 'hiring_candidate_status'
    IDEA_STATUS = 'idea_status'
    IDS_LINK = 'ids_link'
    IDS_PATIENT_LINK = 'ids_patient_link'
    IMPLEMENTATION_STAGE = 'implementation_stage'
    INSURANCE = 'insurance'
    INTERVIEW_AREA = 'interview_area'
    INTERVIEW_QUESTION_SCORE = 'interview_question_score'
    ITERO_SCAN_LINK = 'itero_scan_link'
    JOB_S_APPLIED_TO = 'job_s_applied_to'
    LAB = 'lab'
    LAUNCH_STATUS = 'launch_status'
    LEAD_STATUS = 'lead_status'
    LOCALIZATION_LANGUAGE = 'localization_language'
    LOCALIZATION_MARKET_TEAM = 'localization_market_team'
    LOCALIZATION_STATUS = 'localization_status'
    MEETING_MINUTES = 'meeting_minutes'
    MEETING_NEEDED = 'meeting_needed'
    MINUTES = 'minutes'
    MRR = 'mrr'
    MUST_LOCALIZE = 'must_localize'
    NAME_OF_FOUNDATION = 'name_of_foundation'
    NEED_TO_FOLLOW_UP = 'need_to_follow_up'
    NEXT_APPOINTMENT = 'next_appointment'
    NEXT_STEPS_SALES = 'next_steps_sales'
    NUM_PEOPLE = 'num_people'
    NUMBER_OF_USER_REPORTS = 'number_of_user_reports'
    OFFICE_LOCATION = 'office_location'
    ONBOARDING_ACTIVITY = 'onboarding_activity'
    OWNER = 'owner'
    PARTICIPANTS_NEEDED = 'participants_needed'
    PATIENT_DATE_OF_BIRTH = 'patient_date_of_birth'
    PATIENT_EMAIL = 'patient_email'
    PATIENT_PHONE = 'patient_phone'
    PATIENT_STATUS = 'patient_status'
    PHONE_NUMBER = 'phone_number'
    PLANNING_CATEGORY = 'planning_category'
    POINT_OF_CONTACT = 'point_of_contact'
    POSITION = 'position'
    POST_FORMAT = 'post_format'
    PRESCRIPTION = 'prescription'
    PRIORITY = 'priority'
    PRIORITY_LEVEL = 'priority_level'
    PRODUCT = 'product'
    PRODUCT_STAGE = 'product_stage'
    PROGRESS = 'progress'
    PROJECT_SIZE = 'project_size'
    PROJECT_STATUS = 'project_status'
    PROPOSED_BUDGET = 'proposed_budget'
    PUBLISH_STATUS = 'publish_status'
    REASON_FOR_SCAN = 'reason_for_scan'
    REFERRAL = 'referral'
    REQUEST_TYPE = 'request_type'
    RESEARCH_STATUS = 'research_status'
    RESPONSIBLE_DEPARTMENT = 'responsible_department'
    RESPONSIBLE_TEAM = 'responsible_team'
    RISK_ASSESSMENT_STATUS = 'risk_assessment_status'
    ROOM_NAME = 'room_name'
    SALES_COUNTERPART = 'sales_counterpart'
    SENTIMENT = 'sentiment'
    SHIPPING_LINK = 'shipping_link'
    SOCIAL_CHANNELS = 'social_channels'
    STAGE = 'stage'
    STATUS = 'status'
    STATUS_DESIGN = 'status_design'
    STATUS_OF_INITIATIVE = 'status_of_initiative'
    SYSTEM_SETUP = 'system_setup'
    TASK_PROGRESS = 'task_progress'
    TEAM = 'team'
    TEAM_MARKETING = 'team_marketing'
    TEAM_RESPONSIBLE = 'team_responsible'
    TIME_IT_TAKES_TO_COMPLETE_TASKS = 'time_it_takes_to_complete_tasks'
    TIMEFRAME = 'timeframe'
    TREATMENT_TYPE = 'treatment_type'
    TYPE_WORK_REQUESTS_IT = 'type_work_requests_it'
    USE_AGENCY = 'use_agency'
    USER_NAME = 'user_name'
    VENDOR_CATEGORY = 'vendor_category'
    VENDOR_TYPE = 'vendor_type'
    WORD_COUNT = 'word_count'

class CustomFieldSettingResponseCustomFieldCustomLabelPosition(str, Enum):
    r"""Only relevant for custom fields with `custom` format. This depicts where to place the custom label. This will be null if the `format` is not `custom`."""
    PREFIX = 'prefix'
    SUFFIX = 'suffix'


@dataclass_json(undefined=Undefined.EXCLUDE)

@dataclasses.dataclass
class CustomFieldSettingResponseCustomFieldDateValue:
    r"""*Conditional*. Only relevant for custom fields of type `date`. This object reflects the chosen date (and optionally, time) value of a `date` custom field. If no date is selected, the value of `date_value` will be `null`."""
    date_: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('date'), 'exclude': lambda f: f is None }})
    r"""A string representing the date in YYYY-MM-DD format."""
    date_time: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('date_time'), 'exclude': lambda f: f is None }})
    r"""A string representing the date in ISO 8601 format. If no time value is selected, the value of `date-time` will be `null`."""
    



@dataclass_json(undefined=Undefined.EXCLUDE)

@dataclasses.dataclass
class CustomFieldSettingResponseCustomFieldEnumValue:
    r"""Enum options are the possible values which an enum custom field can adopt. An enum custom field must contain at least 1 enum option but no more than 500.

    You can add enum options to a custom field by using the `POST /custom_fields/custom_field_gid/enum_options` endpoint.

    **It is not possible to remove or delete an enum option**. Instead, enum options can be disabled by updating the `enabled` field to false with the `PUT /enum_options/enum_option_gid` endpoint. Other attributes can be updated similarly.

    On creation of an enum option, `enabled` is always set to `true`, meaning the enum option is a selectable value for the custom field. Setting `enabled=false` is equivalent to “trashing” the enum option in the Asana web app within the “Edit Fields” dialog. The enum option will no longer be selectable but, if the enum option value was previously set within a task, the task will retain the value.

    Enum options are an ordered list and by default new enum options are inserted at the end. Ordering in relation to existing enum options can be specified on creation by using `insert_before` or `insert_after` to reference an existing enum option. Only one of `insert_before` and `insert_after` can be provided when creating a new enum option.

    An enum options list can be reordered with the `POST /custom_fields/custom_field_gid/enum_options/insert` endpoint.
    """
    color: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('color'), 'exclude': lambda f: f is None }})
    r"""The color of the enum option. Defaults to ‘none’."""
    enabled: Optional[bool] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('enabled'), 'exclude': lambda f: f is None }})
    r"""Whether or not the enum option is a selectable value for the custom field."""
    gid: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('gid'), 'exclude': lambda f: f is None }})
    r"""Globally unique identifier of the resource, as a string."""
    name: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('name'), 'exclude': lambda f: f is None }})
    r"""The name of the enum option."""
    resource_type: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('resource_type'), 'exclude': lambda f: f is None }})
    r"""The base type of this resource."""
    


class CustomFieldSettingResponseCustomFieldFormat(str, Enum):
    r"""The format of this custom field."""
    CURRENCY = 'currency'
    IDENTIFIER = 'identifier'
    PERCENTAGE = 'percentage'
    CUSTOM = 'custom'
    NONE = 'none'

class CustomFieldSettingResponseCustomFieldResourceSubtype(str, Enum):
    r"""The type of the custom field. Must be one of the given values."""
    TEXT = 'text'
    ENUM = 'enum'
    MULTI_ENUM = 'multi_enum'
    NUMBER = 'number'
    DATE = 'date'
    PEOPLE = 'people'

class CustomFieldSettingResponseCustomFieldType(str, Enum):
    r"""*Deprecated: new integrations should prefer the resource_subtype field.* The type of the custom field. Must be one of the given values."""
    TEXT = 'text'
    ENUM = 'enum'
    MULTI_ENUM = 'multi_enum'
    NUMBER = 'number'


@dataclass_json(undefined=Undefined.EXCLUDE)

@dataclasses.dataclass
class CustomFieldSettingResponseCustomField:
    r"""Custom Fields store the metadata that is used in order to add user-specified information to tasks in Asana. Be sure to reference the [Custom Fields](/docs/asana-custom-fields) developer documentation for more information about how custom fields relate to various resources in Asana.

    Users in Asana can [lock custom fields](https://asana.com/guide/help/premium/custom-fields#gl-lock-fields), which will make them read-only when accessed by other users. Attempting to edit a locked custom field will return HTTP error code `403 Forbidden`.
    """
    asana_created_field: Optional[CustomFieldSettingResponseCustomFieldAsanaCreatedField] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('asana_created_field'), 'exclude': lambda f: f is None }})
    r"""*Conditional*. A unique identifier to associate this field with the template source of truth."""
    created_by: Optional[shared_usercompact.UserCompact] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('created_by'), 'exclude': lambda f: f is None }})
    currency_code: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('currency_code'), 'exclude': lambda f: f is None }})
    r"""ISO 4217 currency code to format this custom field. This will be null if the `format` is not `currency`."""
    custom_label: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('custom_label'), 'exclude': lambda f: f is None }})
    r"""This is the string that appears next to the custom field value. This will be null if the `format` is not `custom`."""
    custom_label_position: Optional[CustomFieldSettingResponseCustomFieldCustomLabelPosition] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('custom_label_position'), 'exclude': lambda f: f is None }})
    r"""Only relevant for custom fields with `custom` format. This depicts where to place the custom label. This will be null if the `format` is not `custom`."""
    date_value: Optional[CustomFieldSettingResponseCustomFieldDateValue] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('date_value'), 'exclude': lambda f: f is None }})
    r"""*Conditional*. Only relevant for custom fields of type `date`. This object reflects the chosen date (and optionally, time) value of a `date` custom field. If no date is selected, the value of `date_value` will be `null`."""
    description: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('description'), 'exclude': lambda f: f is None }})
    r"""[Opt In](/docs/input-output-options). The description of the custom field."""
    display_value: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('display_value'), 'exclude': lambda f: f is None }})
    r"""A string representation for the value of the custom field. Integrations that don't require the underlying type should use this field to read values. Using this field will future-proof an app against new custom field types."""
    enabled: Optional[bool] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('enabled'), 'exclude': lambda f: f is None }})
    r"""*Conditional*. Determines if the custom field is enabled or not."""
    enum_options: Optional[list[shared_enumoption.EnumOption]] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('enum_options'), 'exclude': lambda f: f is None }})
    r"""*Conditional*. Only relevant for custom fields of type `enum`. This array specifies the possible values which an `enum` custom field can adopt. To modify the enum options, refer to [working with enum options](/docs/create-an-enum-option)."""
    enum_value: Optional[CustomFieldSettingResponseCustomFieldEnumValue] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('enum_value'), 'exclude': lambda f: f is None }})
    format: Optional[CustomFieldSettingResponseCustomFieldFormat] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('format'), 'exclude': lambda f: f is None }})
    r"""The format of this custom field."""
    gid: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('gid'), 'exclude': lambda f: f is None }})
    r"""Globally unique identifier of the resource, as a string."""
    has_notifications_enabled: Optional[bool] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('has_notifications_enabled'), 'exclude': lambda f: f is None }})
    r"""*Conditional*. This flag describes whether a follower of a task with this field should receive inbox notifications from changes to this field."""
    is_global_to_workspace: Optional[bool] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('is_global_to_workspace'), 'exclude': lambda f: f is None }})
    r"""This flag describes whether this custom field is available to every container in the workspace. Before project-specific custom fields, this field was always true."""
    multi_enum_values: Optional[list[shared_enumoption.EnumOption]] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('multi_enum_values'), 'exclude': lambda f: f is None }})
    r"""*Conditional*. Only relevant for custom fields of type `multi_enum`. This object is the chosen values of a `multi_enum` custom field."""
    name: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('name'), 'exclude': lambda f: f is None }})
    r"""The name of the custom field."""
    number_value: Optional[float] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('number_value'), 'exclude': lambda f: f is None }})
    r"""*Conditional*. This number is the value of a `number` custom field."""
    people_value: Optional[list[shared_usercompact.UserCompact]] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('people_value'), 'exclude': lambda f: f is None }})
    r"""*Conditional*. Only relevant for custom fields of type `people`. This array of [compact user](/docs/user-compact) objects reflects the values of a `people` custom field."""
    precision: Optional[int] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('precision'), 'exclude': lambda f: f is None }})
    r"""Only relevant for custom fields of type ‘Number’. This field dictates the number of places after the decimal to round to, i.e. 0 is integer values, 1 rounds to the nearest tenth, and so on. Must be between 0 and 6, inclusive.
    For percentage format, this may be unintuitive, as a value of 0.25 has a precision of 0, while a value of 0.251 has a precision of 1. This is due to 0.25 being displayed as 25%.
    The identifier format will always have a precision of 0.
    """
    resource_subtype: Optional[CustomFieldSettingResponseCustomFieldResourceSubtype] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('resource_subtype'), 'exclude': lambda f: f is None }})
    r"""The type of the custom field. Must be one of the given values."""
    resource_type: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('resource_type'), 'exclude': lambda f: f is None }})
    r"""The base type of this resource."""
    text_value: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('text_value'), 'exclude': lambda f: f is None }})
    r"""*Conditional*. This string is the value of a `text` custom field."""
    type: Optional[CustomFieldSettingResponseCustomFieldType] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('type'), 'exclude': lambda f: f is None }})
    r"""*Deprecated: new integrations should prefer the resource_subtype field.* The type of the custom field. Must be one of the given values."""
    



@dataclass_json(undefined=Undefined.EXCLUDE)

@dataclasses.dataclass
class CustomFieldSettingResponseParent:
    r"""A *project* represents a prioritized list of tasks in Asana or a board with columns of tasks represented as cards. It exists in a single workspace or organization and is accessible to a subset of users in that workspace or organization, depending on its permissions."""
    gid: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('gid'), 'exclude': lambda f: f is None }})
    r"""Globally unique identifier of the resource, as a string."""
    name: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('name'), 'exclude': lambda f: f is None }})
    r"""Name of the project. This is generally a short sentence fragment that fits on a line in the UI for maximum readability. However, it can be longer."""
    resource_type: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('resource_type'), 'exclude': lambda f: f is None }})
    r"""The base type of this resource."""
    



@dataclass_json(undefined=Undefined.EXCLUDE)

@dataclasses.dataclass
class CustomFieldSettingResponseProject:
    r"""A *project* represents a prioritized list of tasks in Asana or a board with columns of tasks represented as cards. It exists in a single workspace or organization and is accessible to a subset of users in that workspace or organization, depending on its permissions."""
    gid: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('gid'), 'exclude': lambda f: f is None }})
    r"""Globally unique identifier of the resource, as a string."""
    name: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('name'), 'exclude': lambda f: f is None }})
    r"""Name of the project. This is generally a short sentence fragment that fits on a line in the UI for maximum readability. However, it can be longer."""
    resource_type: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('resource_type'), 'exclude': lambda f: f is None }})
    r"""The base type of this resource."""
    



@dataclass_json(undefined=Undefined.EXCLUDE)

@dataclasses.dataclass
class CustomFieldSettingResponse:
    r"""Custom Fields Settings objects represent the many-to-many join of the Custom Field and Project as well as stores information that is relevant to that particular pairing."""
    custom_field: Optional[CustomFieldSettingResponseCustomField] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('custom_field'), 'exclude': lambda f: f is None }})
    gid: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('gid'), 'exclude': lambda f: f is None }})
    r"""Globally unique identifier of the resource, as a string."""
    is_important: Optional[bool] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('is_important'), 'exclude': lambda f: f is None }})
    r"""`is_important` is used in the Asana web application to determine if this custom field is displayed in the list/grid view of a project or portfolio."""
    parent: Optional[CustomFieldSettingResponseParent] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('parent'), 'exclude': lambda f: f is None }})
    project: Optional[CustomFieldSettingResponseProject] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('project'), 'exclude': lambda f: f is None }})
    resource_type: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('resource_type'), 'exclude': lambda f: f is None }})
    r"""The base type of this resource."""
    

