"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ..shared import enumoption as shared_enumoption
from dataclasses_json import Undefined, dataclass_json
from enum import Enum
from testing_2 import utils
from typing import Optional

class CustomFieldRequestCustomLabelPosition(str, Enum):
    r"""Only relevant for custom fields with `custom` format. This depicts where to place the custom label. This will be null if the `format` is not `custom`."""
    PREFIX = 'prefix'
    SUFFIX = 'suffix'


@dataclass_json(undefined=Undefined.EXCLUDE)

@dataclasses.dataclass
class CustomFieldRequestDateValue:
    r"""*Conditional*. Only relevant for custom fields of type `date`. This object reflects the chosen date (and optionally, time) value of a `date` custom field. If no date is selected, the value of `date_value` will be `null`."""
    date_: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('date'), 'exclude': lambda f: f is None }})
    r"""A string representing the date in YYYY-MM-DD format."""
    date_time: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('date_time'), 'exclude': lambda f: f is None }})
    r"""A string representing the date in ISO 8601 format. If no time value is selected, the value of `date-time` will be `null`."""
    



@dataclass_json(undefined=Undefined.EXCLUDE)

@dataclasses.dataclass
class CustomFieldRequestEnumValueInput:
    r"""Enum options are the possible values which an enum custom field can adopt. An enum custom field must contain at least 1 enum option but no more than 500.

    You can add enum options to a custom field by using the `POST /custom_fields/custom_field_gid/enum_options` endpoint.

    **It is not possible to remove or delete an enum option**. Instead, enum options can be disabled by updating the `enabled` field to false with the `PUT /enum_options/enum_option_gid` endpoint. Other attributes can be updated similarly.

    On creation of an enum option, `enabled` is always set to `true`, meaning the enum option is a selectable value for the custom field. Setting `enabled=false` is equivalent to “trashing” the enum option in the Asana web app within the “Edit Fields” dialog. The enum option will no longer be selectable but, if the enum option value was previously set within a task, the task will retain the value.

    Enum options are an ordered list and by default new enum options are inserted at the end. Ordering in relation to existing enum options can be specified on creation by using `insert_before` or `insert_after` to reference an existing enum option. Only one of `insert_before` and `insert_after` can be provided when creating a new enum option.

    An enum options list can be reordered with the `POST /custom_fields/custom_field_gid/enum_options/insert` endpoint.
    """
    color: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('color'), 'exclude': lambda f: f is None }})
    r"""The color of the enum option. Defaults to ‘none’."""
    enabled: Optional[bool] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('enabled'), 'exclude': lambda f: f is None }})
    r"""Whether or not the enum option is a selectable value for the custom field."""
    name: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('name'), 'exclude': lambda f: f is None }})
    r"""The name of the enum option."""
    


class CustomFieldRequestFormat(str, Enum):
    r"""The format of this custom field."""
    CURRENCY = 'currency'
    IDENTIFIER = 'identifier'
    PERCENTAGE = 'percentage'
    CUSTOM = 'custom'
    NONE = 'none'

class CustomFieldRequestResourceSubtype(str, Enum):
    r"""The type of the custom field. Must be one of the given values."""
    TEXT = 'text'
    ENUM = 'enum'
    MULTI_ENUM = 'multi_enum'
    NUMBER = 'number'
    DATE = 'date'
    PEOPLE = 'people'


@dataclass_json(undefined=Undefined.EXCLUDE)

@dataclasses.dataclass
class CustomFieldRequestInput:
    r"""Custom Fields store the metadata that is used in order to add user-specified information to tasks in Asana. Be sure to reference the [Custom Fields](/docs/asana-custom-fields) developer documentation for more information about how custom fields relate to various resources in Asana.

    Users in Asana can [lock custom fields](https://asana.com/guide/help/premium/custom-fields#gl-lock-fields), which will make them read-only when accessed by other users. Attempting to edit a locked custom field will return HTTP error code `403 Forbidden`.
    """
    workspace: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('workspace') }})
    r"""*Create-Only* The workspace to create a custom field in."""
    currency_code: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('currency_code'), 'exclude': lambda f: f is None }})
    r"""ISO 4217 currency code to format this custom field. This will be null if the `format` is not `currency`."""
    custom_label: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('custom_label'), 'exclude': lambda f: f is None }})
    r"""This is the string that appears next to the custom field value. This will be null if the `format` is not `custom`."""
    custom_label_position: Optional[CustomFieldRequestCustomLabelPosition] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('custom_label_position'), 'exclude': lambda f: f is None }})
    r"""Only relevant for custom fields with `custom` format. This depicts where to place the custom label. This will be null if the `format` is not `custom`."""
    date_value: Optional[CustomFieldRequestDateValue] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('date_value'), 'exclude': lambda f: f is None }})
    r"""*Conditional*. Only relevant for custom fields of type `date`. This object reflects the chosen date (and optionally, time) value of a `date` custom field. If no date is selected, the value of `date_value` will be `null`."""
    description: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('description'), 'exclude': lambda f: f is None }})
    r"""[Opt In](/docs/input-output-options). The description of the custom field."""
    enabled: Optional[bool] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('enabled'), 'exclude': lambda f: f is None }})
    r"""*Conditional*. Determines if the custom field is enabled or not."""
    enum_options: Optional[list[shared_enumoption.EnumOptionInput]] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('enum_options'), 'exclude': lambda f: f is None }})
    r"""*Conditional*. Only relevant for custom fields of type `enum`. This array specifies the possible values which an `enum` custom field can adopt. To modify the enum options, refer to [working with enum options](/docs/create-an-enum-option)."""
    enum_value: Optional[CustomFieldRequestEnumValueInput] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('enum_value'), 'exclude': lambda f: f is None }})
    format: Optional[CustomFieldRequestFormat] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('format'), 'exclude': lambda f: f is None }})
    r"""The format of this custom field."""
    has_notifications_enabled: Optional[bool] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('has_notifications_enabled'), 'exclude': lambda f: f is None }})
    r"""*Conditional*. This flag describes whether a follower of a task with this field should receive inbox notifications from changes to this field."""
    multi_enum_values: Optional[list[shared_enumoption.EnumOptionInput]] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('multi_enum_values'), 'exclude': lambda f: f is None }})
    r"""*Conditional*. Only relevant for custom fields of type `multi_enum`. This object is the chosen values of a `multi_enum` custom field."""
    name: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('name'), 'exclude': lambda f: f is None }})
    r"""The name of the custom field."""
    number_value: Optional[float] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('number_value'), 'exclude': lambda f: f is None }})
    r"""*Conditional*. This number is the value of a `number` custom field."""
    people_value: Optional[list[str]] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('people_value'), 'exclude': lambda f: f is None }})
    r"""*Conditional*. Only relevant for custom fields of type `people`. This array of user GIDs reflects the users to be written to a `people` custom field. Note that *write* operations will replace existing users (if any) in the custom field with the users specified in this array."""
    precision: Optional[int] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('precision'), 'exclude': lambda f: f is None }})
    r"""Only relevant for custom fields of type ‘Number’. This field dictates the number of places after the decimal to round to, i.e. 0 is integer values, 1 rounds to the nearest tenth, and so on. Must be between 0 and 6, inclusive.
    For percentage format, this may be unintuitive, as a value of 0.25 has a precision of 0, while a value of 0.251 has a precision of 1. This is due to 0.25 being displayed as 25%.
    The identifier format will always have a precision of 0.
    """
    resource_subtype: Optional[CustomFieldRequestResourceSubtype] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('resource_subtype'), 'exclude': lambda f: f is None }})
    r"""The type of the custom field. Must be one of the given values."""
    text_value: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('text_value'), 'exclude': lambda f: f is None }})
    r"""*Conditional*. This string is the value of a `text` custom field."""
    

