"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from dataclasses_json import Undefined, dataclass_json
from testing_2 import utils


@dataclass_json(undefined=Undefined.EXCLUDE)

@dataclasses.dataclass
class GoalRemoveSupportingRelationshipRequest:
    supporting_resource: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('supporting_resource') }})
    r"""The gid of the supporting resource to remove from the parent goal. Must be the gid of a goal, project, or portfolio."""
    

