"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from dataclasses_json import Undefined, dataclass_json
from testing_2 import utils
from typing import Optional


@dataclass_json(undefined=Undefined.EXCLUDE)

@dataclasses.dataclass
class ProjectSectionInsertRequest:
    project: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('project') }})
    r"""The project in which to reorder the given section."""
    section: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('section') }})
    r"""The section to reorder."""
    after_section: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('after_section'), 'exclude': lambda f: f is None }})
    r"""Insert the given section immediately after the section specified by this parameter."""
    before_section: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('before_section'), 'exclude': lambda f: f is None }})
    r"""Insert the given section immediately before the section specified by this parameter."""
    

