"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from dataclasses_json import Undefined, dataclass_json
from testing_2 import utils
from typing import Optional


@dataclass_json(undefined=Undefined.EXCLUDE)

@dataclasses.dataclass
class SectionRequest:
    name: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('name') }})
    r"""The text to be displayed as the section name. This cannot be an empty string."""
    insert_after: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('insert_after'), 'exclude': lambda f: f is None }})
    r"""An existing section within this project after which the added section should be inserted. Cannot be provided together with insert_before."""
    insert_before: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('insert_before'), 'exclude': lambda f: f is None }})
    r"""An existing section within this project before which the added section should be inserted. Cannot be provided together with insert_after."""
    

