"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from dataclasses_json import Undefined, dataclass_json
from testing_2 import utils
from typing import Optional


@dataclass_json(undefined=Undefined.EXCLUDE)

@dataclasses.dataclass
class TaskCountResponse:
    r"""A response object returned from the task count endpoint."""
    num_completed_milestones: Optional[int] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('num_completed_milestones'), 'exclude': lambda f: f is None }})
    r"""The number of completed milestones in a project."""
    num_completed_tasks: Optional[int] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('num_completed_tasks'), 'exclude': lambda f: f is None }})
    r"""The number of completed tasks in a project."""
    num_incomplete_milestones: Optional[int] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('num_incomplete_milestones'), 'exclude': lambda f: f is None }})
    r"""The number of incomplete milestones in a project."""
    num_incomplete_tasks: Optional[int] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('num_incomplete_tasks'), 'exclude': lambda f: f is None }})
    r"""The number of incomplete tasks in a project."""
    num_milestones: Optional[int] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('num_milestones'), 'exclude': lambda f: f is None }})
    r"""The number of milestones in a project."""
    num_tasks: Optional[int] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('num_tasks'), 'exclude': lambda f: f is None }})
    r"""The number of tasks in a project."""
    

